# 异常机制

和Java相比，C#没有受检查异常，因此也没有throws关键字，个人认为这是个糟糕的设计，因为编译器不能帮助我们检查某些必要的异常处理是否编写好了。而Java中，一些老旧的库过度使用了受检查异常，这是库编写的问题，而不是受检查异常机制设计的不好。

C#中，所有异常继承于`System.Exception`，其下有两个子类`SystemException`和`ApplicationException`，我们自定义的异常通常继承`ApplicationException`。

C#也有`try...catch...finally...`机制，和Java相同。

## 异常捕获

下面例子我们捕获一个除以零异常：

```csharp
using System;

namespace demo01
{
    class Program
    {
        static void Main(string[] args)
        {
            int i = 1;
            int j = 0;
            try
            {
                int k = i / j;
            }
            catch (DivideByZeroException ex)
            {
                Console.WriteLine("\nMessage ---\n{0}", ex.Message);
                Console.WriteLine("\nHelpLink ---\n{0}", ex.HelpLink);
                Console.WriteLine("\nSource ---\n{0}", ex.Source);
                Console.WriteLine("\nStackTrace ---\n{0}", ex.StackTrace);
                Console.WriteLine("\nTargetSite ---\n{0}", ex.TargetSite);
            }
            finally
            {
                Console.WriteLine("finally执行");
            }

            Console.ReadLine();
        }
    }
}
```

注意异常对象`ex`的用法，`ex`中有一些定义好的字段，用来存储异常的各种信息：异常消息，错误栈等，我们可以按需取用。

## 抛出异常

和Java中一样，抛出异常使用`throw`关键字，抛出一个异常对象就行了。下面例子代码中，抛出了一个`ApplicationException`，并使用`try...catch...`捕获：

```csharp
using System;

namespace demo01
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                throw new ApplicationException();
            }
            catch (Exception ex)
            {
                Console.WriteLine("\nMessage ---\n{0}", ex.Message);
                Console.WriteLine("\nHelpLink ---\n{0}", ex.HelpLink);
                Console.WriteLine("\nSource ---\n{0}", ex.Source);
                Console.WriteLine("\nStackTrace ---\n{0}", ex.StackTrace);
                Console.WriteLine("\nTargetSite ---\n{0}", ex.TargetSite);
            }

            Console.ReadLine();
        }
    }
}
```
